global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mq-ingestion-emea'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mq-ingestion-emea:8081']

  - job_name: 'mq-ingestion-nam'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mq-ingestion-nam:8082']

  - job_name: 'mq-ingestion-aspac'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mq-ingestion-aspac:8083']
