server:
  port: 8081

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mq-ingestion-service}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC}
    region: ${APP_KAFKA_REGION}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  health:
    kafka:
      enabled: true
