server:
  port: 8081

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mq-ingestion-service}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC}
    region: ${APP_KAFKA_REGION}

ibm:
  mq:
    queue-manager: ${IBM_MQ_QUEUE_MANAGER}
    channel: ${IBM_MQ_CHANNEL}
    conn-name: ${IBM_MQ_CONN_NAME}
    queue: ${IBM_MQ_QUEUE}
    user: ${IBM_MQ_USER}
    password: ${IBM_MQ_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    region: ${APP_KAFKA_REGION}
    version: 1.0.0
