server:
  port: 8081

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:mq-ingestion-service}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topic: ${APP_KAFKA_TOPIC:raw-payments-emea}
    region: ${APP_KAFKA_REGION:EMEA}

ibm:
  mq:
    queue-manager: ${IBM_MQ_QUEUE_MANAGER:QM1}
    channel: ${IBM_MQ_CHANNEL:DEV.APP.SVRCONN}
    conn-name: ${IBM_MQ_CONN_NAME:ibm-mq:1414}
    queue: ${IBM_MQ_QUEUE:TEST.QUEUE}
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:passw0rd}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    name: ${SPRING_APPLICATION_NAME:mq-ingestion-service}
    version: 1.0.0
    region: ${APP_KAFKA_REGION:EMEA}
