server:
  port: 8081

spring:
  application:
    name: mq-ingestion-service

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topic: raw-payments-emea
    region: EMEA
